"""
logging_config.py
------------------
One-time logging setup, called once at process start by app.py.

Two guarantees this provides, both important for a tool that handles
customer PII and API credentials:

  1. A `RedactingFilter` runs on every log record and re-redacts any
     `extra={...}` fields that look like a payload or request params,
     even if a caller forgot to pre-redact. This is deliberately
     redundant with callers using src.security.redact_for_logging()
     before logging -- defense in depth, not a replacement for it. If
     both layers redact, nothing is lost; if a future call site forgets
     the first layer, this one still catches it.

  2. Every pipeline run gets a correlation_id (see new_correlation_id())
     threaded through fetch -> validate -> transform -> submit, so a
     support engineer reading the log file can filter to one integration
     run and see the full story. Currently generated by pipeline.py via
     uuid.uuid4() directly -- new_correlation_id() is provided here as
     the canonical way to generate one, for any future caller that needs
     it outside the pipeline module.
"""

from __future__ import annotations

import logging
import os
import uuid
from logging.handlers import RotatingFileHandler

from src.security import redact_for_logging

_SENSITIVE_EXTRA_KEYS = {"payload", "params"}
_CONFIGURED = False


class RedactingFilter(logging.Filter):
    """
    Belt-and-suspenders redaction at the logging layer itself.

    Callers (api_client.py, destination_client.py) already pass
    pre-redacted dicts via redact_for_logging() before calling
    logger.info(). This filter re-applies the same redaction to any
    `payload` or `params` extra field regardless, so a call site that
    forgets to redact upstream still can't leak a credential into a
    log file.
    """
    def filter(self, record: logging.LogRecord) -> bool:
        for key in _SENSITIVE_EXTRA_KEYS:
            value = getattr(record, key, None)
            if isinstance(value, dict):
                setattr(record, key, redact_for_logging(value))
        return True


class _ExtraFormatter(logging.Formatter):
    """Appends any `extra={...}` fields as a readable dict after the base message."""
    def format(self, record: logging.LogRecord) -> str:
        base = f"{self.formatTime(record, self.datefmt)} | {record.levelname} | {record.name} | {record.getMessage()}"
        extras = {
            k: v for k, v in record.__dict__.items()
            if k not in logging.LogRecord.__dict__
            and k not in ("message", "asctime")
            and not k.startswith("_")
        }
        if extras:
            base += f" | {extras}"
        return base


def new_correlation_id() -> str:
    """Canonical way to generate a correlation ID for a new pipeline run."""
    return uuid.uuid4().hex[:12]


def configure_logging(log_level: str = "INFO", log_file_path: str = "logs/integration.log") -> None:
    """
    Configure the root 'integration' logger tree. Idempotent -- safe to
    call multiple times (Streamlit reruns app.py's top-level code on
    every widget interaction) without stacking duplicate handlers or
    producing repeated log lines.
    """
    global _CONFIGURED
    if _CONFIGURED:
        return

    log_dir = os.path.dirname(log_file_path)
    if log_dir:
        os.makedirs(log_dir, exist_ok=True)

    logger = logging.getLogger("integration")
    logger.setLevel(log_level.upper())
    logger.handlers.clear()

    formatter = _ExtraFormatter(datefmt="%Y-%m-%dT%H:%M:%S")
    redacting_filter = RedactingFilter()

    console_handler = logging.StreamHandler()
    console_handler.setFormatter(formatter)
    console_handler.addFilter(redacting_filter)
    logger.addHandler(console_handler)

    file_handler = RotatingFileHandler(
        log_file_path, maxBytes=2_000_000, backupCount=3, encoding="utf-8",
    )
    file_handler.setFormatter(formatter)
    file_handler.addFilter(redacting_filter)
    logger.addHandler(file_handler)

    # Without this, records also propagate up to the root logger, and
    # Streamlit installs its own root-logger handlers -- you'd get either
    # duplicated lines or noisy interleaving with Streamlit's internal
    # logging. This is what prevents that.
    logger.propagate = False

    _CONFIGURED = True